document.getElementById("states").addEventListener("change", function() {
    // Get the selected state code
    var stateCode = this.value;

    // Map of state codes to their corresponding image URLs
    var stateImages = {
        "al": "url('img/al@2x.jpg')",
        "ak": "url('img/ak@2x.jpg')",
        "az": "url('img/az@2x.jpg')",
        "ar": "url('img/ar@2x.jpg')",
        "ca": "url('img/ca@2x.jpg')",
        "co": "url('img/co@2x.jpg')",
        "ct": "url('img/ct@2x.jpg')",
        "de": "url('img/de@2x.jpg')",
        "dc": "url('img/dc@2x.jpg')",
        "fl": "url('img/fl@2x.jpg')",
        "ga": "url('img/ga@2x.jpg')",
        "hi": "url('img/hi@2x.jpg')",
        "id": "url('img/id@2x.jpg')",
        "il": "url('img/il@2x.jpg')",
        "in": "url('img/in@2x.jpg')",
        "ia": "url('img/ia@2x.jpg')",
        "ks": "url('img/ks@2x.jpg')",
        "ky": "url('img/ky@2x.jpg')",
        "la": "url('img/la@2x.jpg')",
        "me": "url('img/me@2x.jpg')",
        "md": "url('img/md@2x.jpg')",
        "ma": "url('img/ma@2x.jpg')",
        "mi": "url('img/mi@2x.jpg')",
        "mn": "url('img/mn@2x.jpg')",
        "ms": "url('img/ms@2x.jpg')",
        "mo": "url('img/mo@2x.jpg')",
        "mt": "url('img/mt@2x.jpg')",
        "ne": "url('img/ne@2x.jpg')",
        "nv": "url('img/nv@2x.jpg')",
        "nh": "url('img/nh@2x.jpg')",
        "nj": "url('img/nj@2x.jpg')",
        "nm": "url('img/nm@2x.jpg')",
        "ny": "url('img/ny@2x.jpg')",
        "nc": "url('img/nc@2x.jpg')",
        "nd": "url('img/nd@2x.jpg')",
        "oh": "url('img/oh@2x.jpg')",
        "ok": "url('img/ok@2x.jpg')",
        "or": "url('img/or@2x.jpg')",
        "pa": "url(''img/pa@2x.jpg)",
        "ri": "url('img/ri@2x.jpg')",
        "sc": "url('img/sc@2x.jpg')",
        "sd": "url('img/sd@2x.jpg')",
        "tn": "url('img/tn@2x.jpg')",
        "tx": "url('img/tx@2x.jpg')",
        "ut": "url('img/ut@2x.jpg')",
        "vt": "url('img/vt@2x.jpg')",
        "va": "url('img/va@2x.jpg')",
        "wa": "url('img/wa@2x.jpg')",
        "wv": "url('img/wv@2x.jpg')",
        "wi": "url('img/wi@2x.jpg')",
        "wy": "url('img/wy@2x.jpg')"
    };

    // Map of state codes to their names
    var stateNames = {
        "al": "Alabama",
        "ak": "Alaska",
        "az": "Arizona",
        "ar": "Arkansas",
        "ca": "California",
        "co": "Colorado",
        "ct": "Connecticut",
        "de": "Delaware",
        "dc": "District of Columbia",
        "fl": "Florida",
        "ga": "Georgia",
        "hi": "Hawaii",
        "id": "Idaho",
        "il": "Illinois",
        "in": "Indiana",
        "ia": "Iowa",
        "ks": "Kansas",
        "ky": "Kentucky",
        "la": "Louisiana",
        "me": "Maine",
        "md": "Maryland",
        "ma": "Massachusetts",
        "mi": "Michigan",
        "mn": "Minnesota",
        "ms": "Mississippi",
        "mo": "Missouri",
        "mt": "Montana",
        "ne": "Nebraska",
        "nv": "Nevada",
        "nh": "New Hampshire",
        "nj": "New Jersey",
        "nm": "New Mexico",
        "ny": "New York",
        "nc": "North Carolina",
        "nd": "North Dakota",
        "oh": "Ohio",
        "ok": "Oklahoma",
        "or": "Oregon",
        "pa": "Pennsylvania",
        "ri": "Rhode Island",
        "sc": "South Carolina",
        "sd": "South Dakota",
        "tn": "Tennessee",
        "tx": "Texas",
        "ut": "Utah",
        "vt": "Vermont",
        "va": "Virginia",
        "wa": "Washington",
        "wv": "West Virginia",
        "wi": "Wisconsin",
        "wy": "Wyoming"
    };

    // Change the background image of the postcard
    var postcard = document.getElementById("postcard");
    postcard.style.backgroundImage = stateImages[stateCode] || "url('../img/empty-state.jpg')";

    // Change the state name in the postcard
    var stateHeading = document.getElementById("state-heading");
    stateHeading.textContent = stateNames[stateCode] || "Choose a state";
});
